# Generated by Django 4.1.2 on 2022-10-16 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'access_level',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='ServerData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=15)),
                ('port', models.IntegerField()),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'server_data',
                'unique_together': {('ip', 'port')},
            },
        ),
        migrations.CreateModel(
            name='NewsData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('topic', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('id_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dreamapp.account')),
            ],
            options={
                'db_table': 'news_data',
            },
        ),
        migrations.CreateModel(
            name='ServerAccessLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_access_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreamapp.accesslevel')),
                ('id_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreamapp.serverdata')),
            ],
            options={
                'db_table': 'server_access_level',
                'unique_together': {('id_server', 'id_access_level')},
            },
        ),
        migrations.CreateModel(
            name='FriendList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='dreamapp.account')),
                ('id_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='dreamapp.account')),
            ],
            options={
                'db_table': 'friend_list',
                'unique_together': {('id_owner', 'id_friend')},
            },
        ),
        migrations.CreateModel(
            name='AccountAccessLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_access_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreamapp.accesslevel')),
                ('id_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dreamapp.account')),
            ],
            options={
                'db_table': 'account_access_level',
                'unique_together': {('id_account', 'id_access_level')},
            },
        ),
    ]
