# Generated by Django 4.1.2 on 2022-10-17 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreamapp', '0002_alter_accesslevel_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountaccesslevel',
            old_name='id_access_level',
            new_name='access_level',
        ),
        migrations.RenameField(
            model_name='accountaccesslevel',
            old_name='id_account',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='friendlist',
            old_name='id_friend',
            new_name='friend',
        ),
        migrations.RenameField(
            model_name='friendlist',
            old_name='id_owner',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='newsdata',
            old_name='id_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='serveraccesslevel',
            old_name='id_access_level',
            new_name='access_level',
        ),
        migrations.RenameField(
            model_name='serveraccesslevel',
            old_name='id_server',
            new_name='server',
        ),
        migrations.AlterUniqueTogether(
            name='accountaccesslevel',
            unique_together={('account', 'access_level')},
        ),
        migrations.AlterUniqueTogether(
            name='friendlist',
            unique_together={('owner', 'friend')},
        ),
        migrations.AlterUniqueTogether(
            name='serveraccesslevel',
            unique_together={('server', 'access_level')},
        ),
    ]
